### ISSUE TITLE
Add sparse fieldset support.

### ISSUE THREAD

**Issue by alanpeabody** [AgilionApps/ja_serializer#11]
http://jsonapi.org/format/#fetching-sparse-fieldsets

Should we accept the raw param?

Or a formatted list like:
```elixir
PostSerializer.format(model, conn, fields: [post: [:title, :published_at]])
```

**Comment by green-arrow** [comment]
I would prefer more of a raw param to keep the controllers thin. However, when using Plug, the query params come in a Map when first calling `fetch_query_params`:

```elixir
%{"fields" => %{"articles" => "title,body", "people" => "name"}}
```

In order to get raw params, the user would have to parse out the query string directly. 

That being said, I think it would be nice if we could just pass the result of `conn.query_params.fields` to the formatter. That behavior would match how the optional includes piece works (passing `conn.query_params.include` as the `include` opt). The difference would be that, in the serializer, we would be working with a Map instead of a string.

Thoughts?

**Comment by alanpeabody** [comment]
Yup, I agree, lets make it easy for users.
