### ISSUE TITLE
Preload not working

### ISSUE THREAD

**Issue by nicooga** [AgilionApps/ja_serializer#169]
I'm using `preload/3` but it doesn't seem to be working.

~~~elixir
defmodule DabliuEx.CatalogView do
  use DabliuEx.Web, :jsonapi_view

  attributes ~w(name)a
  has_many :items, serializer: DabliuEx.Catalog.ItemView

  def preload(record_or_records, _conn, include_opts) do
    IO.puts("I WAS CALLED") # This is being called
    record_or_records |> DabliuEx.Repo.preload(include_opts)
  end
end
~~~

When I hit the API I'm building with ´include: [:items]´ it throws:

> The catalog relationship returned %Ecto.Association.NotLoaded{}.

Defining `items/2` solves the issue:

~~~elixir
  def items(struct, _conn) do
    struct |> DabliuEx.Repo.preload(:items)
  end
~~~

However, I understood `preload/3` it's meant for preloading the relationships and it is actually being called as I  detected with my sophisticated debugging technique.

## Context

mix.lock:

~~~js
  "ja_resource": {:git, "https://github.com/AgilionApps/ja_resource.git", "d64a13d31c6e3d366a9133675403f863f814b4ea", []},
  "ja_serializer": {:hex, :ja_serializer, "0.11.0", "6c8ded7cfd4cd226812e97445bedd2f6d47e19c5d8b987f58cf552518c98fbd1", [:mix], [{:inflex, "~> 1.4", [hex: :inflex, optional: false]}, {:plug, "> 1.0.0", [hex: :plug, optional: false]}, {:poison, "~> 1.4 or ~> 2.0", [hex: :poison, optional: false]}, {:scrivener, "~> 1.2 or ~> 2.0", [hex: :scrivener, optional: true]}]},
~~~

**Comment by alanpeabody** [comment]
Thanks for the report @nicooga.

Do the include opts need some manipulation before being passed to preload?

For example does the following work?

```elixir
  def preload(record_or_records, _conn, _include_opts) do
    record_or_records |> DabliuEx.Repo.preload(:items)
  end
```

**Comment by nicooga** [comment]
No It doesn't change things to define `preload/3` like that.

**Comment by nicooga** [comment]
I just realized that the problem was on the child module ´Catalog.ItemView´ not defining well the relationship:

~~~elixir
defmodule DabliuEx.Catalog.ItemView do
  use DabliuEx.Web, :jsonapi_view

  attributes ~w(position image)a
  has_one :catalog, serializer: DabliuEx.CatalogView
end
~~~

I needed to add the `field` attribute to make it work since it is actually a "belongs_to" association:

 ~~~elixir
has_one :catalog, serializer: DabliuEx.CatalogView
~~~

I think adding a `belongs_to` macro could save this confusion for future users. What do you think?

**Comment by alanpeabody** [comment]
I don't think that is doing what you want TBH.

field is just the source for the data, if you want it included it should be `catalog`, if you don't want it included but do want the resource identifier then `field: :catalog_id` without the serializer is okay.

There are lot of ways to handle relationships with json-api, as they all (has_many, has_one, belongs_to) really behave the same if anything I would like to drop down to one macro. If it becomes a problem to define exactly what you want using the macro I suggest using the relationship/2 callback instead.

I am going to close this because the preload hook is working, but please do post if you have more questions.
